-- Migration 0005: G3 checkpoint 4, round-9 remediation -- lock-granularity-vs-revocation-blast-
-- radius, DEFENSE-IN-DEPTH layer (architect, internal review MAJOR #3, the finding explicitly
-- flagged as needing Google's own primary documentation opened before deciding, per this project's
-- evidence-over-inference discipline -- not GPT-PM's or this module's own prior restatement of it).
--
-- Verified against the primary source (developers.google.com/identity/protocols/oauth2/native-app,
-- "Token revocation" section, fetched and independently re-confirmed 2026-09-13):
--   "Revocation removes all OAuth 2.0 scopes previously granted to a project, invalidating any
--    issued access or refresh tokens for all clients registered under that project."
--   "Following a successful revocation response, it might take some time before the revocation has
--    full effect."
-- This CONFIRMS (not merely restates) oauth.ts's existing "project-wide, not scoped to one token"
-- claim and the propagation-delay claim behind REVOKE_PROPAGATION_BUFFER_MS.
--
-- **Round 10 correction, important: this index is NOT the synchronization primitive, and round 9's
-- own header comment here overstated what it closes.** GPT-PM's round-9 full-sweep review (see
-- migration 0004's own header, and core/DECISION_LOG.md) demonstrated this index does not actually
-- close the cross-`source_account_id` revocation race: the real failure shape is TWO different
-- `source_account_id` rows for the SAME Google identity, one (A) disconnecting/revoking while the
-- other (B) is independently mid-`exchangeCode()`. If A's disconnect completes -- revoking at
-- Google AND deleting A's `gmail_connections` row -- BEFORE B's own write lands, this index sees no
-- conflict at all (A's row is already gone), so B's write succeeds, reporting CONNECTED with a
-- credential that may already be invalidated by A's revoke. A UNIQUE index can only reject two rows
-- that exist AT THE SAME TIME; it cannot serialize operations that never overlap in the table but
-- DO overlap at Google.
--
-- The actual fix (migration 0004, this round): `gmail_oauth_lifecycle` is now a project-wide
-- singleton lock, so A's disconnect and B's connect genuinely contend on the SAME lock regardless
-- of `source_account_id` -- this closes the race migration 0004's own header describes in full.
--
-- This index REMAINS as defense in depth (GPT-PM's own words: "The unique-email index can remain
-- defense in depth, but it cannot be the synchronization primitive") -- it still prevents two
-- `source_account_id` rows from both holding a persisted, simultaneously-live connection to the
-- same Gmail address via any path that bypasses the lifecycle lock (a bug elsewhere, a manual DB
-- edit, a future code path that forgets to acquire the lock) -- but the project-wide lock in
-- migration 0004 is what actually enforces the invariant during normal operation.
CREATE UNIQUE INDEX idx_gmail_connections_unique_email ON gmail_connections(LOWER(gmail_email));
